### ISSUE TITLE
AttributeError: 'Response' object has no attribute 'status'

### ISSUE THREAD

**Issue by hendrix84** [aishee/bitforce#1]
15ZSGqVXEtqYhmWTG57WjcP4A78d3GNFyz = 0
1Pwsq6Ucmw6QDFpS61NTwpWVcrLQ41GaAB = 0
1Pj3coz9YYPmoorh4oWrTPcZ36iU8V3DVf = 0
1Q1WW9kimoFyiuJ3njkpNQbQnUcGPrsrrp = 0
Traceback (most recent call last):
  File "./bitforce.py", line 105, in <module>
    main()
  File "./bitforce.py", line 86, in main
    data[3] = balance(data[2])
  File "./bitforce.py", line 69, in balance
    and APIGet.status != 429):
AttributeError: 'Response' object has no attribute 'status'

**Comment by ghost** [comment]
Line 69 (bitforce.py)
```diff
-            and APIGet.status != 429):
+            and APIGet.status_code != 429):
```

**Comment by aishee** [comment]
I will review. project no long maintain!

**Comment by aishee** [comment]
Bug report.
